openapi: "3.0.0"
info:
  title: example API
  version: "1.0.0"
paths:
  /test:
    get:
      responses:
        "200":
          description: an operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  modified_at:
                    type: string
                    format: date-time
