openapi: "3.0.0"
info:
  title: example API
  version: "1.0.0"
tags:
  - name: a
  - name: b
paths:
  /endpoint1:
    get:
      tags:
        - a
      responses:
        "200":
          description: 
  /endpoint2:
    get:
      tags:
        - b
      responses:
        "200":
          description: 
