#%Validation Profile 1.0

profile: Test 8

description: testing complex paths, alterantive paths

violation:
  - validation1

validations:

  validation1:
    targetClass: apiContract.Operation
    message: Scalars in parameters must have minLength defined
    propertyConstraints:
      apiContract.expects / (apiContract.parameter / shapes.schema | apiContract.payload / raml-shapes.schema / shacl.property / raml-shapes.range) :
        nested:
          propertyConstraints:
            shacl.minLength:
              minCount: 1