openapi: "3.0.0"
info:
  title: example API
  version: "1.0.0"
paths:
  /test:
    get:
      parameters:
        - name: a
          in: query
          schema:
            type: string
      responses:
        "200":
          description: a response
